### ISSUE TITLE
dependency result reversed

### ISSUE THREAD

**Issue by tigersniffs** [jillesvangurp/spring-depend#3]
@Bean("shiroFilter")
@DependsOn("securityManager")
public ShiroFilterFactoryBean shiroFilter(DefaultSecurityManager securityManager){
        ShiroFilterFactoryBean shiroFilter  = new ShiroFilterFactoryBean();
        shiroFilter.setSecurityManager(securityManager);
}
when I used the above code,the result is  "CREATE (securityManager)-[:DEPENDSON]->(shiroFilter)"

the correct dependency relation should be   shiroFilter depends on securityManager
I think because the shiroFilter used securityManager,so the securityManager should be loaded by spring earlier than shiroFIlter.It 's should be like securityManager DEPENDSON shiroFilter.

**Comment by jillesvangurp** [comment]
Maybe you have a circular dependency?

**Comment by tigersniffs** [comment]
Yes , there is a circular dependency.
So I try to figure out what make this siuation with your tool. 
I expected that i can see something from result like " A DEPENDSON B ,B DEPENDSON  A " .( supposed A and B make  circular dependency).
but i didn't see that. That's why I opend this issue.
By the way.  In the end, I find the reason. Just because the spring boot version.  Same code can run in former version,but will make  circular dependency in latter version
